#!/bin/false

import os
import os.path
import glob


Import('env')

dir_path = Dir('.').abspath

env.example_sources = sorted(glob.glob(dir_path + "/*.cpp"))
env.example_headers = sorted(glob.glob(dir_path + "/*.h"))
