#!/bin/false

import os
import os.path
import glob


Import('env')

dir_path = Dir('.').abspath

env.daemon_sources += sorted(glob.glob(dir_path + "/*.cpp"))
env.daemon_headers += sorted(glob.glob(dir_path + "/*.h"))
