#!/bin/false

import os
import os.path
import glob


Import('env')

dir_path = Dir('.').abspath

env.sources += sorted(glob.glob(dir_path + "/*.cpp"))
env.headers += sorted(glob.glob(dir_path + "/*.h"))
env.render_headers += sorted(glob.glob(dir_path + "/render/*.h"))

env.common_sources += sorted(glob.glob(dir_path + "/common/*.cpp"))
env.common_headers += sorted(glob.glob(dir_path + "/common/*.h"))
